### ISSUE TITLE
Music player is laggy

### ISSUE THREAD

**Issue by ghost** [AsmSafone/RadioPlayer#5]
Good work on this handy bot. However, the output is laggy. Is there any way to reduce music quality?

**Comment by AsmSafone** [comment]
I will try my best. btw try to host on vps. It's known that vc bots are lags on heroku cz of low cpu resources :(

**Comment by ghost** [comment]
Okay thank you very much. If I reduce the quality of the raw_file outputted by ffmpeg, do you think it will help?

**Comment by AsmSafone** [comment]
Maybe. Didn't tested yet!

**Comment by ghost** [comment]
Okay, awesome project btw.
